Better place for this bit.

diff --git a/files/shell_conf/funcs_alias b/files/shell_conf/funcs_alias
--- a/files/shell_conf/funcs_alias
+++ b/files/shell_conf/funcs_alias
@@ -436,6 +436,20 @@ fi
 if valid_name tabs; then
     tabs 4
 fi
+
+# Fetch terminal information
+if [ ! -d ~/.terminfo ]; then
+    if ! valid_name curl || ! valid_name gunzip || ! valid_name tic; then
+        echo "No terminfo, missing one of: curl, gunzip, tic"
+    fi
+
+    echo "Getting terminfo."
+    # Taken from nvim | :h $TERM
+    curl -L http://invisible-island.net/datafiles/current/terminfo.src.gz | gunzip > /tmp/term.src
+    tic /tmp/term.src
+    command rm /tmp/term.src
+fi
+
 #}}}
 
 # vim:set filetype=sh foldmethod=marker:
